### PR TITLE
Few fixes and updates for 0.6

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
v0.2.jl file simply won't load under 0.6 and segfaults (see the JLD issue)  in addition the following lines  with typevars also do not work  on 0.6
```julia
typevar = Array{Int}[[1]]
typevar_lb = Vector{TypeVar(:U, Integer)}[[1]]
typevar_ub = Vector{TypeVar(:U, Int, Any)}[[1]]
typevar_lb_ub = Vector{TypeVar(:U, Int, Real)}[[1]]

        @check fidr typevar
        @check fidr typevar_lb
        @check fidr typevar_ub
        @check fidr typevar_lb_ub
```

**Comment by timholy** [comment]
These changes to the code seem fine. For the typevars, I think
```julia
julia> V = Vector{T} where Int<:T<:Real
Array{T,1} where Int64<:T<:Real

julia> V[[1]]
1-element Array{Array{T,1} where Int64<:T<:Real,1}:
 [1]
```
works.

I don't think I have time to debug the access violation. You might try commenting out various lines of `jldopen` until you know what's triggering it.

**Comment by musm** [comment]
That doesn't seem to fix things
e.g.

```julia
    typevar_lb_ub = (Vector{T} where Int<:T<:Real)[[1]]

    @check fidr typevar_lb_ub

WARNING: Error reading typevar_lb_ub
ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{Int64,1} to an object of type Array{Int64<:U<:Real,1}
This may have arisen from a call to the constructor Array{Int64<:U<:Real,1}(...),
since type constructors fall back to convert methods.
```

can't seem to figure these out so I will just merge these changes for now

**Comment by timholy** [comment]
It's a bit of a surprising error, since
```julia
julia> (Vector{T} where Int<:T<:Real)[[1]]
1-element Array{Array{T,1} where Int64<:T<:Real,1}:
 [1]

julia> convert(Vector{T} where Int<:T<:Real, [1])
1-element Array{Int64,1}:
 1
```

Most importantly, thanks for doing as much as you have! HDF/JLD are clearly benefiting a lot from your efforts!

**Pull request merged**
