### PR TITLE
Fix 0.4 deprecated bindings

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
Would be nice to have travis enabled for this repo as well so that I can know whether this breaks 0.3 ....

**Comment by timholy** [comment]
Good point. I'll move this to JuliaLang, too.

**Comment by timholy** [comment]
Come to think of it, this seems too messy to have on JuliaLang. I'll transfer to JuliaIO instead.

**Comment by timholy** [comment]
OK, if you do a force-push it should run.

**Comment by yuyichao** [comment]
Pushed. There seems to be an intermittent failure according to https://github.com/JuliaLang/JLD.jl/pull/27 though.... = = ...

**Comment by timholy** [comment]
Thanks.

> There seems to be an intermittent failure according to JuliaLang/JLD.jl#27 though.... = = ...

Julia 0.3, what's that? :wink:

**Pull request merged**
