### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by tkelman** [comment]
if you leave the script section out then the default is equivalent to this, so it's not required to write it out every time

**Comment by musm** [comment]
I think there is some issue with the default in this case since there is no `src` directory. See the previous log files for example (before this PR) : https://travis-ci.org/JuliaIO/JLDArchives.jl/jobs/192471329

**Comment by tkelman** [comment]
oh yeah you're right, didn't realize this isn't a real julia package

**Comment by musm** [comment]
I just double checked, it definitely is needed in this case. This PR is g2g, I want to test JLD  bugfixes so it would be nice to not have to wait

**Comment by musm** [comment]
Bump

**Comment by musm** [comment]
Needs a good old squash and merge fyi

**Pull request merged**
